"""Batch-generate AI rationales for every company missing one, resumably.

Reuses app.py's existing rationale logic verbatim -- get_ai_rationale(), which
carries its own _build_rationale_prompt() and the Gemini -> Groq -> Cerebras
RATIONALE_PROVIDERS fallback chain, and which already writes each result to
.rationale_cache.json as it goes. No new prompt, no new provider-calling code:
importing the real thing is what guarantees a batch-generated rationale is
identical to one generated by clicking through the Streamlit app.

Resumability comes for free from that same cache: get_ai_rationale() returns the
cached value on a hit without calling any provider, so re-running this script
after an interruption, a rate-limit wall, or a crash costs nothing for the
companies already done and simply continues with the rest. There is no "start
over" state -- the cache IS the progress.

Pacing: ~2,000 companies against three free tiers will hit rate limits if driven
flat out. A deliberate delay sits between calls, and a run of consecutive
failures (the signature of hitting a wall on every provider at once) backs off
progressively rather than burning through the remaining companies logging
identical errors. Any single company's failure is logged and skipped -- one bad
company never aborts the run.

Run from the repo root:
    python3 batch_generate_rationale.py [--limit N] [--delay SECONDS]

    --limit N    stop after N successful generations this run (for a smoke test,
                 or to deliberately stop short of a provider's daily quota)
    --delay S    seconds between provider calls (default 2.0)

Writes:
    .rationale_cache.json            appended in place, after every success
    data/quality_reports/rationale_batch_log_<date>.csv    per-company outcome
"""

import argparse
import csv
import sys
import time
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

# app.py is a Streamlit script: importing it executes module-level Streamlit
# calls. Those are harmless outside a Streamlit runtime (they no-op or warn to
# stderr) and this is deliberately preferred over copy-pasting the prompt and
# provider chain into this file, which would let the two drift apart silently.
from app import (  # noqa: E402
    get_ai_rationale,
    _load_rationale_cache,
    load_universe,
    METRICS,
)
from src.logic.scoring import score_companies  # noqa: E402

LOG_DIR = REPO_ROOT / "data" / "quality_reports"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / f"rationale_batch_log_{datetime.now().strftime('%Y-%m-%d')}.csv"

# Consecutive-failure backoff. A single failure is usually one bad company; a
# run of them means every provider is rate-limiting or down, and hammering
# through the remaining ~2,000 companies at full speed would just deepen the
# block. Sleep grows with the streak, capped so an unattended run still recovers
# on its own if the limit is a rolling per-minute one.
BACKOFF_AFTER_CONSECUTIVE_FAILURES = 3
BACKOFF_SECONDS = [30, 60, 120, 300]
STOP_AFTER_CONSECUTIVE_FAILURES = 40


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--delay", type=float, default=2.0)
    args = parser.parse_args()

    print("Loading universe ...")
    df = load_universe()
    # get_ai_rationale()'s prompt needs score + pctl_<metric> columns, which are
    # weight-dependent. Equal weights match export_for_frontend.py's own choice,
    # so a batch-generated rationale describes the same percentiles a visitor
    # sees on the default (unweighted) tear sheet.
    equal_weights = {m: 5 for m in METRICS}
    df = score_companies(df, equal_weights)
    print(f"{len(df)} companies loaded.")

    cache = _load_rationale_cache()
    print(f"{len(cache)} rationales already cached.\n")

    pending = [
        row
        for _, row in df.iterrows()
        if f"{row['symbol']}|{row['as_of_date']}" not in cache
    ]
    print(f"{len(pending)} companies still need a rationale.")
    if args.limit:
        print(f"--limit {args.limit}: will stop after {args.limit} successes this run.")
    print()

    generated = failed = 0
    consecutive_failures = 0
    log_is_new = not LOG_PATH.exists()

    with LOG_PATH.open("a", newline="", encoding="utf-8") as log_file:
        writer = csv.writer(log_file)
        if log_is_new:
            writer.writerow(["timestamp", "symbol", "name", "outcome", "detail"])

        for i, row in enumerate(pending, 1):
            symbol = row["symbol"]
            try:
                text = get_ai_rationale(row)
            except Exception as exc:  # never let one company abort the run
                text = None
                detail = f"{type(exc).__name__}: {str(exc)[:160]}"
            else:
                detail = "" if text else "all providers returned nothing"

            now = datetime.now().isoformat(timespec="seconds")
            if text:
                generated += 1
                consecutive_failures = 0
                writer.writerow([now, symbol, row["name"], "generated", ""])
                print(f"  [{i}/{len(pending)}] {symbol}: ok ({generated} generated)")
            else:
                failed += 1
                consecutive_failures += 1
                writer.writerow([now, symbol, row["name"], "failed", detail])
                print(f"  [{i}/{len(pending)}] {symbol}: FAILED -- {detail}")
            log_file.flush()  # progress survives a kill -9, same as the cache

            if args.limit and generated >= args.limit:
                print(f"\nReached --limit {args.limit}, stopping.")
                break

            if consecutive_failures >= STOP_AFTER_CONSECUTIVE_FAILURES:
                print(
                    f"\n{consecutive_failures} consecutive failures -- every provider "
                    f"appears to be rate-limited or down. Stopping rather than burning "
                    f"through the remaining companies. Re-run later to resume."
                )
                break

            if consecutive_failures >= BACKOFF_AFTER_CONSECUTIVE_FAILURES:
                idx = min(
                    consecutive_failures - BACKOFF_AFTER_CONSECUTIVE_FAILURES,
                    len(BACKOFF_SECONDS) - 1,
                )
                wait = BACKOFF_SECONDS[idx]
                print(f"    ({consecutive_failures} in a row -- backing off {wait}s)")
                time.sleep(wait)
            else:
                time.sleep(args.delay)

    total_cached = len(_load_rationale_cache())
    print("\n=== Done ===")
    print(f"Generated this run: {generated}")
    print(f"Failed this run:    {failed}")
    print(f"Total cached now:   {total_cached} / {len(df)}")
    print(f"Log: {LOG_PATH}")
    if total_cached < len(df):
        print(
            f"\n{len(df) - total_cached} still missing -- re-run this script to resume "
            f"exactly where it stopped (cached companies are skipped without any "
            f"provider call)."
        )


if __name__ == "__main__":
    main()
