"""Batch-generate two AI fields per company -- "about" and "why_this_score" --
for every company missing them, resumably.

Reuses app.py's existing logic verbatim: get_ai_analysis(), which carries its
own _build_analysis_prompt() and the same Gemini -> Groq -> Cerebras
RATIONALE_PROVIDERS fallback chain get_ai_rationale() already used, and which
writes each result to .rationale_cache.json as it goes. No new prompt-building
or provider-calling code lives in this file: importing the real thing is what
guarantees a batch-generated result is identical to one generated by clicking
through the Streamlit app. get_ai_analysis() asks each provider for both
fields in a single call (one prompt, one structured JSON response) rather than
two separate calls, to conserve free-tier quota.

Resumability comes for free from that same cache: get_ai_analysis() returns
the cached value on a hit without calling any provider, so re-running this
script after an interruption, a rate-limit wall, or a crash costs nothing for
the companies already done and simply continues with the rest. There is no
"start over" state -- the cache IS the progress. "Done" here means a company
has BOTH about and why_this_score cached under the current TAXONOMY_VERSION
-- an old single-field `rationale` from before the sector_v2 taxonomy switch
does not count, since TAXONOMY_VERSION baking into the cache key is what
invalidates rationale text written against a since-changed peer group (see
get_ai_rationale()'s own comment in app.py). That old rationale isn't
discarded, though: get_ai_analysis() carries it forward into the new cache
entry as a `rationale` fallback/reference field, and only ever writes a fresh
why_this_score, never a copy of it.

Pacing: ~2,000 companies against three free tiers will hit rate limits if driven
flat out. A deliberate delay sits between calls, and a run of consecutive
failures (the signature of hitting a wall on every provider at once) backs off
progressively rather than burning through the remaining companies logging
identical errors. Any single company's failure is logged and skipped -- one bad
company never aborts the run.

Run from the repo root:
    python3 batch_generate_rationale.py [--limit N] [--delay SECONDS]

    --limit N    stop after N successful generations this run (for a smoke test,
                 or to deliberately stop short of a provider's daily quota)
    --delay S    seconds between provider calls (default 2.0)

Writes:
    .rationale_cache.json            appended in place, after every success
    data/quality_reports/rationale_batch_log_<date>.csv    per-company outcome
"""

import argparse
import atexit
import csv
import os
import sys
import time
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

# app.py is a Streamlit script: importing it executes module-level Streamlit
# calls. Those are harmless outside a Streamlit runtime (they no-op or warn to
# stderr) and this is deliberately preferred over copy-pasting the prompt and
# provider chain into this file, which would let the two drift apart silently.
from app import (  # noqa: E402
    get_ai_analysis,
    _load_rationale_cache,
    load_universe,
    METRICS,
    TAXONOMY_VERSION,
)
from src.logic.scoring import score_companies  # noqa: E402

LOG_DIR = REPO_ROOT / "data" / "quality_reports"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / f"rationale_batch_log_{datetime.now().strftime('%Y-%m-%d')}.csv"

# Consecutive-failure backoff. A single failure is usually one bad company; a
# run of them means every provider is rate-limiting or down, and hammering
# through the remaining ~2,000 companies at full speed would just deepen the
# block. Sleep grows with the streak, capped so an unattended run still recovers
# on its own if the limit is a rolling per-minute one.
BACKOFF_AFTER_CONSECUTIVE_FAILURES = 3
BACKOFF_SECONDS = [30, 60, 120, 300]
STOP_AFTER_CONSECUTIVE_FAILURES = 40

# Separate from app.py's RATIONALE_CACHE_LOCK_PATH (an flock held only for the
# instant of a merge-write). This one is a PID sentinel held for the entire
# run, so a second `python3 batch_generate_rationale.py` started by accident
# in another terminal -- confirmed as the likely cause of ~94 companies
# losing an already-successful generation to the old unlocked blind-overwrite
# save -- refuses to start instead of racing the first instance.
PID_LOCK_PATH = REPO_ROOT / ".batch_generate_rationale.pid"


def _pid_is_running(pid):
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True  # exists, just owned by another user
    return True


def _release_run_lock():
    try:
        if PID_LOCK_PATH.exists() and PID_LOCK_PATH.read_text().strip() == str(os.getpid()):
            PID_LOCK_PATH.unlink()
    except OSError:
        pass


def _acquire_run_lock():
    if PID_LOCK_PATH.exists():
        try:
            existing_pid = int(PID_LOCK_PATH.read_text().strip())
        except (ValueError, OSError):
            existing_pid = None
        if existing_pid and _pid_is_running(existing_pid):
            print(
                f"Another batch_generate_rationale.py is already running (PID {existing_pid}).\n"
                f"Refusing to start a second instance -- running two at once against the same "
                f".rationale_cache.json is the confirmed likely cause of ~94 companies silently "
                f"losing an already-successful generation earlier.\n"
                f"Let the existing run finish, or if you're certain PID {existing_pid} is dead, "
                f"remove {PID_LOCK_PATH} yourself and re-run."
            )
            sys.exit(1)
        # Lock file's PID is no longer running -- stale, safe to reclaim.
    PID_LOCK_PATH.write_text(str(os.getpid()))
    atexit.register(_release_run_lock)


def _cache_key(row):
    return f"{row['symbol']}|{row['as_of_date']}|{TAXONOMY_VERSION}"


def _is_done(cache, row):
    """True once both fields are cached under the CURRENT taxonomy version --
    matches exactly what get_ai_analysis() itself treats as a cache hit."""
    entry = cache.get(_cache_key(row))
    return isinstance(entry, dict) and bool(entry.get("about")) and bool(entry.get("why_this_score"))


def _count_done(cache, df):
    return sum(1 for _, row in df.iterrows() if _is_done(cache, row))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--delay", type=float, default=2.0)
    parser.add_argument(
        "--tickers-file", type=str, default=None,
        help="CSV with a 'symbol' column -- restrict this run to exactly these "
             "tickers, skipping the rest of the universe regardless of their "
             "current cache status.",
    )
    args = parser.parse_args()

    _acquire_run_lock()

    print("Loading universe ...")
    df = load_universe()
    # get_ai_analysis()'s prompt needs score + pctl_<metric> columns, which are
    # weight-dependent. Equal weights match export_for_frontend.py's own choice,
    # so a batch-generated result describes the same percentiles a visitor
    # sees on the default (unweighted) tear sheet.
    equal_weights = {m: 5 for m in METRICS}
    df = score_companies(df, equal_weights)
    print(f"{len(df)} companies loaded.")

    cache = _load_rationale_cache()
    done_count = _count_done(cache, df)
    print(f"{done_count} companies already have about + why_this_score cached "
          f"(taxonomy {TAXONOMY_VERSION}).\n")

    pending = [row for _, row in df.iterrows() if not _is_done(cache, row)]

    if args.tickers_file:
        with open(args.tickers_file, newline="", encoding="utf-8") as f:
            allowlist = {r["symbol"].strip() for r in csv.DictReader(f) if r.get("symbol", "").strip()}
        pending = [row for row in pending if row["symbol"] in allowlist]
        already_done_in_allowlist = len(allowlist) - len(pending)
        print(
            f"--tickers-file {args.tickers_file}: {len(allowlist)} tickers listed, "
            f"{already_done_in_allowlist} of them already done, {len(pending)} pending -- "
            f"skipping the rest of the universe."
        )

    print(f"{len(pending)} companies still need generation.")
    if args.limit:
        print(f"--limit {args.limit}: will stop after {args.limit} successes this run.")
    print()

    generated = failed = 0
    consecutive_failures = 0
    log_is_new = not LOG_PATH.exists()

    with LOG_PATH.open("a", newline="", encoding="utf-8") as log_file:
        writer = csv.writer(log_file)
        if log_is_new:
            writer.writerow(["timestamp", "symbol", "name", "outcome", "detail"])

        for i, row in enumerate(pending, 1):
            symbol = row["symbol"]
            try:
                result = get_ai_analysis(row)
            except Exception as exc:  # never let one company abort the run
                result = None
                detail = f"{type(exc).__name__}: {str(exc)[:160]}"
            else:
                detail = "" if result else "all providers returned nothing (or unparseable)"

            now = datetime.now().isoformat(timespec="seconds")
            if result:
                generated += 1
                consecutive_failures = 0
                writer.writerow([now, symbol, row["name"], "generated", ""])
                print(f"  [{i}/{len(pending)}] {symbol}: ok ({generated} generated)")
            else:
                failed += 1
                consecutive_failures += 1
                writer.writerow([now, symbol, row["name"], "failed", detail])
                print(f"  [{i}/{len(pending)}] {symbol}: FAILED -- {detail}")
            log_file.flush()  # progress survives a kill -9, same as the cache

            if args.limit and generated >= args.limit:
                print(f"\nReached --limit {args.limit}, stopping.")
                break

            if consecutive_failures >= STOP_AFTER_CONSECUTIVE_FAILURES:
                print(
                    f"\n{consecutive_failures} consecutive failures -- every provider "
                    f"appears to be rate-limited or down. Stopping rather than burning "
                    f"through the remaining companies. Re-run later to resume."
                )
                break

            if consecutive_failures >= BACKOFF_AFTER_CONSECUTIVE_FAILURES:
                idx = min(
                    consecutive_failures - BACKOFF_AFTER_CONSECUTIVE_FAILURES,
                    len(BACKOFF_SECONDS) - 1,
                )
                wait = BACKOFF_SECONDS[idx]
                print(f"    ({consecutive_failures} in a row -- backing off {wait}s)")
                time.sleep(wait)
            else:
                time.sleep(args.delay)

    total_done = _count_done(_load_rationale_cache(), df)
    print("\n=== Done ===")
    print(f"Generated this run: {generated}")
    print(f"Failed this run:    {failed}")
    print(f"Total done now:     {total_done} / {len(df)}")
    print(f"Log: {LOG_PATH}")
    if total_done < len(df):
        print(
            f"\n{len(df) - total_done} still missing -- re-run this script to resume "
            f"exactly where it stopped (companies already done are skipped without any "
            f"provider call)."
        )


if __name__ == "__main__":
    main()
